# this is how your .side.yml should look like
capabilities:
    browserName: "Chrome"
    browser_version: '81.0'
    os: "Windows"
    os_version: '10'
    resolution: '1024x768'
    name: 'Selenium IDE automate test'
    browserstack.debug: true
    browserstack.console: "verbose"
    browserstack.networkLogs: trueee
server: "https://mohammedk1:spBCpUJaVTnvxxssFtEJ@hub-cloud.browserstack.com/wd/hub"
